# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190504_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='iamge',
            new_name='image',
        ),
    ]
